# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Structured outputs backed by compile-time JSON schemas.

The agents' output types are annotated with ``@JsonSchema``, so Micronaut JSON
Schema generates their schemas (including the docstrings as descriptions)
while processing. ``SchemaAwareChatModel`` decorates whichever ``ChatModel``
bean the application uses: it advertises JSON-schema structured output and
replaces the schema LangChain4j derives reflectively from the return type with
the generated one.
"""

from __future__ import annotations

import json
import logging
import threading
from typing import Any

from dev.langchain4j.model.chat import Capability, ChatModel
from dev.langchain4j.model.chat.request import (
    ChatRequest,
    ResponseFormat,
    ResponseFormatType,
)
from dev.langchain4j.model.chat.request.json import (
    JsonAnyOfSchema,
    JsonArraySchema,
    JsonBooleanSchema,
    JsonEnumSchema,
    JsonIntegerSchema,
    JsonNullSchema,
    JsonNumberSchema,
    JsonObjectSchema,
    JsonSchema,
    JsonStringSchema,
)
from dev.langchain4j.model.chat.response import ChatResponse
from jakarta.inject import Singleton
from java.util import HashSet, List
from micronaut.context.event import BeanCreatedEvent, BeanCreatedEventListener
from micronaut.jsonschema.utils import JsonSchemaClassPathResourceLoader

LOG = logging.getLogger(__name__)


class GeneratedJsonSchemas:
    """The JSON schemas generated by Micronaut JSON Schema, indexed by title (the class name)."""

    def __init__(self, loader: JsonSchemaClassPathResourceLoader):
        self._loader = loader
        self._by_title: dict[str, dict[str, Any]] | None = None
        self._by_id: dict[str, dict[str, Any]] = {}
        self._converted: dict[str, Any] = {}
        self._lock = threading.Lock()

    def _load(self) -> dict[str, dict[str, Any]]:
        with self._lock:
            if self._by_title is None:
                by_title: dict[str, dict[str, Any]] = {}
                for entry in self._loader.jsonSchemas().entrySet():
                    stream = entry.getValue().asInputStream()
                    try:
                        schema = json.loads(bytes(stream.readAllBytes()).decode("utf-8"))
                    finally:
                        stream.close()
                    if "title" in schema:
                        by_title[schema["title"]] = schema
                    if "$id" in schema:
                        self._by_id[schema["$id"]] = schema
                LOG.info("Loaded %d generated JSON schemas for structured outputs", len(by_title))
                self._by_title = by_title
            return self._by_title

    def schema_for(self, title: str) -> Any | None:
        """The LangChain4j ``JsonSchema`` for a generated schema title, or ``None``."""
        schemas = self._load()
        with self._lock:
            if title not in self._converted:
                source = schemas.get(title)
                self._converted[title] = (
                    JsonSchema.builder().name(title).rootElement(self._element(source)).build()
                    if source is not None else None
                )
            return self._converted[title]

    def _element(self, schema: dict[str, Any]) -> Any:
        """Converts a JSON Schema document (draft 2020-12 subset) into LangChain4j schema elements."""
        if "$ref" in schema:
            target = self._by_id.get(schema["$ref"])
            if target is None:
                raise ValueError(f"Unresolved JSON schema reference {schema['$ref']}")
            return self._element(target)
        description = schema.get("description")
        if "enum" in schema:
            return JsonEnumSchema.builder().description(description).enumValues(List.of(*[str(v) for v in schema["enum"]])).build()
        if "anyOf" in schema or "oneOf" in schema:
            variants = [self._element(s) for s in schema.get("anyOf") or schema.get("oneOf")]
            return JsonAnyOfSchema.builder().description(description).anyOf(List.of(*variants)).build()

        schema_type = schema.get("type", "object")
        if isinstance(schema_type, list):
            # Nullable types are expressed as ["string", "null"]; models only need the value type
            non_null = [t for t in schema_type if t != "null"]
            schema_type = non_null[0] if non_null else "null"

        if schema_type == "object":
            builder = JsonObjectSchema.builder().description(description)
            for name, property_schema in (schema.get("properties") or {}).items():
                builder.addProperty(name, self._element(property_schema))
            if schema.get("required"):
                builder.required(List.of(*schema["required"]))
            if "additionalProperties" in schema and isinstance(schema["additionalProperties"], bool):
                builder.additionalProperties(schema["additionalProperties"])
            return builder.build()
        if schema_type == "array":
            return JsonArraySchema.builder().description(description).items(self._element(schema.get("items") or {})).build()
        if schema_type == "string":
            return JsonStringSchema.builder().description(description).build()
        if schema_type == "integer":
            return JsonIntegerSchema.builder().description(description).build()
        if schema_type == "number":
            return JsonNumberSchema.builder().description(description).build()
        if schema_type == "boolean":
            return JsonBooleanSchema.builder().description(description).build()
        if schema_type == "null":
            return JsonNullSchema()
        raise ValueError(f"Unsupported JSON schema type {schema_type!r}")


class SchemaAwareChatModel(ChatModel):
    """Decorates a ``ChatModel`` so structured outputs use the compile-time JSON schemas."""

    def __init__(self, delegate: Any, schemas: GeneratedJsonSchemas):
        self.delegate = delegate
        self.schemas = schemas

    def supportedCapabilities(self):
        capabilities = HashSet(self.delegate.supportedCapabilities())
        capabilities.add(Capability.RESPONSE_FORMAT_JSON_SCHEMA)
        return capabilities

    def defaultRequestParameters(self):
        return self.delegate.defaultRequestParameters()

    def listeners(self):
        return self.delegate.listeners()

    def provider(self):
        return self.delegate.provider()

    def doChat(self, chat_request: ChatRequest) -> ChatResponse:
        return self.delegate.chat(self._with_generated_schema(chat_request))

    def _with_generated_schema(self, chat_request: ChatRequest) -> ChatRequest:
        response_format = chat_request.responseFormat()
        if response_format is None or response_format.jsonSchema() is None:
            return chat_request
        name = str(response_format.jsonSchema().name())
        generated = self.schemas.schema_for(name)
        if generated is None:
            LOG.debug("No generated JSON schema for '%s'; using LangChain4j's schema", name)
            return chat_request
        generated_format = ResponseFormat.builder().type(ResponseFormatType.JSON).jsonSchema(generated).build()
        return chat_request.toBuilder().responseFormat(generated_format).build()


@Singleton
class SchemaAwareChatModelDecorator(BeanCreatedEventListener[ChatModel]):
    """Wraps every ``ChatModel`` bean (Gemini, OpenAI, a test double, ...) with ``SchemaAwareChatModel``."""

    def __init__(self, loader: JsonSchemaClassPathResourceLoader):
        self.schemas = GeneratedJsonSchemas(loader)

    def onCreated(self, event: BeanCreatedEvent[ChatModel]) -> ChatModel:
        model = event.getBean()
        if isinstance(model, SchemaAwareChatModel):
            return model
        return SchemaAwareChatModel(model, self.schemas)
